spring:
  datasource:
    url: jdbc:postgresql://localhost:5422/orderdb?currentSchema=order_service
    username: orderservice
    password: orderservice
  flyway:
    enabled: true

order-service:
  price-feed-url: http://localhost:8089/prices