package com.bogdanenache.order_service.exception;

public enum ErrorCode {
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR,
    TYPE_MISMATCH,
    CONSTRAINT_VIOLATION,
    NOT_FOUND,
    CONFLICT,
    INTERNAL_ERROR,
    VALIDATION_ERROR,
    MISSING_PARAMETER,
    MALFORMED_JSON,
    UNPROCESSABLE_ENTITY,
    SERVICE_UNAVAILABLE,
    TOO_MANY_REQUESTS
}
