CREATE TABLE ORDER_SERVICE.EXECUTIONS
(
    EXC_ID           NUMERIC(10, 0)                 NOT NULL,
    EXC_INTERNAL_ID  CHARACTER VARYING(36)          NOT NULL,
    ORD_ORDER_ID     NUMERIC(10, 0)                 NOT NULL,
    EXC_PRICE        NUMERIC(100, 6)                NOT NULL,
    EXC_CREATED      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    EXC_VERSION      NUMERIC(6, 0)                  NOT NULL
) WITH (
      OIDS = FALSE
    );

ALTER TABLE ORDER_SERVICE.EXECUTIONS
    ADD CONSTRAINT PK_EXECUTION PRIMARY KEY (EXC_ID);

ALTER TABLE ORDER_SERVICE.EXECUTIONS
    ADD CONSTRAINT FK_ORDER_EXECUTION_01 FOREIGN KEY (ORD_ORDER_ID)
        REFERENCES ORDER_SERVICE.ORDERS (ORD_ID) ON DELETE NO ACTION;


ALTER TABLE ORDER_SERVICE.EXECUTIONS
    ADD CONSTRAINT CHK_EXECUTION_01 UNIQUE (EXC_INTERNAL_ID);

CREATE SEQUENCE IF NOT EXISTS ORDER_SERVICE.SEQ_EXC_ID
    INCREMENT BY 2
    START WITH 1
    MAXVALUE 9999999999
    MINVALUE 1
    NO CYCLE
    CACHE 20;

