CREATE TABLE ORDER_SERVICE.ORDERS
(
    ORD_ID              NUMERIC(10, 0)        NOT NULL,
    ORD_INTERNAL_ID     CHARACTER VARYING(36) NOT NULL,
    ORD_ACCOUNT_ID      CHARACTER VARYING(36) NOT NULL,
    ORD_SYMBOL          CHARACTER VARYING(20) NOT NULL,
    ORD_SIDE            CHARACTER VARYING(20) NOT NULL,
    ORD_QUANTITY        CHARACTER VARYING(8),
    ORD_STATUS          CHARACTER VARYING(11),
    ORD_CREATED         TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    ORD_VERSION         NUMERIC(6, 0)         NOT NULL,
    ORD_IDEMPOTENCY_KEY CHARACTER VARYING(36) NOT NULL
) WITH (
      OIDS = FALSE
      );

ALTER TABLE ORDER_SERVICE.ORDERS
    ADD CONSTRAINT PK_ORDER PRIMARY KEY (ORD_ID);

ALTER TABLE ORDER_SERVICE.ORDERS
    ADD CONSTRAINT CHK_ORDER_01 CHECK (ORD_SIDE IN ('BUY', 'SELL')) NOT VALID;

ALTER TABLE ORDER_SERVICE.ORDERS
    ADD CONSTRAINT CHK_ORDER_02 CHECK (ORD_STATUS IN ('PROCESSED', 'FAILED')) NOT VALID;

ALTER TABLE ORDER_SERVICE.ORDERS
    ADD CONSTRAINT CHK_ORDER_03 UNIQUE (ORD_INTERNAL_ID);

ALTER TABLE ORDER_SERVICE.ORDERS
    ADD CONSTRAINT UQ_ORD_IDEMPOTENCY_KEY UNIQUE (ORD_IDEMPOTENCY_KEY);

CREATE SEQUENCE IF NOT EXISTS ORDER_SERVICE.SEQ_ORD_ID
    INCREMENT BY 2
    START WITH 1
    MAXVALUE 9999999999
    MINVALUE 1
    NO CYCLE
    CACHE 20;


